apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "scalyr-k8snode-manager.fullname" . }}
  labels:
    {{- include "scalyr-k8snode-manager.labels" . | nindent 4 }}
rules:
  - verbs:
      - list
    resources:
      - nodes
    apiGroups:
      - ""

