apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalyr-k8snode-manager.fullname" . }}
  labels:
    {{- include "scalyr-k8snode-manager.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config.scalyr.config }}
  "{{ $key }}": |
    {{ if $.Values.config.scalyr.base64Config }}{{ $value | b64dec }}{{ else }}{{ $value }}{{ end }}
    {{- end }}
