apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scalyr-k8snode-manager.fullname" . }}
  labels:
    {{- include "scalyr-k8snode-manager.labels" . | nindent 4 }}
data:
  key: "{{- .Values.config.sshKey }}"
